name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate SVG
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Generate SVG
        uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push SVG to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Pacman Contribution Graph"
          add: "output/*.svg"
